name: test-bun

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.2, latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate layouts
        run: bun run generate --input Manoonchai.json

      - name: Generate ColemakDH layout
        run: bun run generate --input Manoonchai-ColemakDH-ZXCVD.json

      - name: Run tests with coverage
        run: bun test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v5
